services:
  mariadb:
    container_name: 'mariadb'
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_NAME: ${MYSQL_NAME}
        MYSQL_ROOTPASS: ${MYSQL_ROOTPASS}
        MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
        MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    image: 'mariadb'
    volumes:
      - database:/var/lib/mysql/
    networks:
      - cloud1
    restart: always
  wordpress:
    container_name: 'wordpress'
    build:
      context: ./requirements/wordpress/
      args:
        MYSQL_NAME: ${MYSQL_NAME}
        MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
        MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
        MYSQL_HOST: ${MYSQL_HOST}
        WEB_TITLE: ${WEB_TITLE}
        WEB_EMAIL: ${WEB_EMAIL}
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: 'wordpress'
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
      MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
      MYSQL_HOST: ${MYSQL_HOST}
      WEB_TITLE: ${WEB_TITLE}
      WEB_EMAIL: ${WEB_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - cloud1
    restart: always
    depends_on:
      - mariadb
  nginx:
    container_name: 'nginx'
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: 'nginx'
    volumes:
      - wordpress:/var/www/wordpress/
      - phpmyadmin:/var/www/phpmyadmin/
    networks:
      - cloud1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - wordpress
      - mariadb
      - phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./requirements/phpmyadmin
    image: 'phpmyadmin'
    volumes:
      - phpmyadmin:/var/www/phpmyadmin/
    networks:
      - cloud1
    restart: always
    depends_on:
      - wordpress

# volumes:
#   database:
#     name: database
#     driver: local
#     driver_opts:
#       type: none
#       o: "bind"
#       device: $HOME/cloud1_data/database/
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       type: none
#       o: "bind"
#       device: $HOME/cloud1_data/www/wordpress/
#   phpmyadmin:
#     name: phpmyadmin
#     driver: local
#     driver_opts:
#       type: none
#       o: "bind"
#       device: $HOME/cloud1_data/www/phpmyadmin/

volumes:
  database:
  wordpress:
  phpmyadmin:

networks:
  cloud1:
    name: cloud1
    driver: bridge