version: 0.0
os: linux

files:
  - source: docker
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts/down-docker.sh
      runas: root
  AfterInstall:
    
  # Install:
  ApplicationStart:
    - location: scripts/start-docker.sh
      runas: root