version: 0.0
os: linux

files:
  - source: srcs
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts/down-docker.sh
  AfterInstall:
    - location: scripts/prepare-env.sh
  ApplicationStart:
    - location: scripts/start-docker.sh