version: 0.0
os: linux

files:
  - source: docker
    destination: /usr/src/app
hooks:
  BeforeInstall:
    - location: scripts/install-docker.sh
      runas: root
  # Install:
  ApplicationStart:
    - location: scripts/start-docker.sh
      runas: root