version: "3.9"

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 3360:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    environment:
      - DB_HOST
      - DB_NAME
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_DOMAIN
      - WP_SCHEME
      - WP_PORT
      - WP_TITLE
      - WP_ADMIN
      - WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_EMAIL
      - WP_USER_PASSWORD
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
    depends_on:
      - wordpress
    restart: always

networks:
  wordpress:

volumes:
  wordpress:
  db:


